name: Node.js Compatibility
description: Report an incompatibility with the Node.js API
labels: ['compatibility']
body:
    - type: input
      label: ZenFS Version
      description: The latest version the issue occurs on
      placeholder: 1.2.3
      required: true

    - type: input
      label: Node.js Version
      description: What version of Node.js the incompatibility is with
      placeholder: 22.0.0
      required: true

    - type: textarea
      label: Minimal reproduction
      description: 'A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)'
      render: typescript

    - type: textarea
      label: Node.js' behavior

    - type: textarea
      label: ZenFS' behavior

    - type: textarea
      label: Additional context
