name: Node.js Compatibility
description: Report an incompatibility with the Node.js API
labels: ['compatibility']
body:
    - type: input
      attributes:
          label: ZenFS Version
          description: The latest version the issue occurs on
          placeholder: 1.2.3
      validations:
          required: true

    - type: input
      attributes:
          label: Node.js Version
          description: What version of Node.js the incompatibility is with
          placeholder: 22.0.0
      validations:
          required: true

    - type: textarea
      attributes:
          label: Minimal reproduction
          description: 'A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)'
          render: typescript

    - type: textarea
      attributes:
          label: Node.js' behavior

    - type: textarea
      attributes:
          label: ZenFS' behavior

    - type: textarea
      attributes:
          label: Additional context
