name: Docs
on:
    workflow_dispatch:
    workflow_call:
        secrets:
            DOCS_DISPATCH_TOKEN:
                description: Token with write access to docs repo, used to trigger a docs rebuild.
                required: false

jobs:
    dispatch:
        runs-on: ubuntu-latest
        name: Trigger docs rebuild
        steps:
            - name: Dispatch
              env:
                  GH_TOKEN: ${{ secrets.DOCS_DISPATCH_TOKEN }}
              run: |
                  if [ -z "$GH_TOKEN" ]; then
                      echo "::warning::DOCS_DISPATCH_TOKEN is not set, docs will not be automatically updated."
                      exit 0
                  fi
                  echo "{\"event_type\":\"docs\",\"client_payload\":{\"repository\":\"$GITHUB_REPOSITORY\",\"ref\":\"$GITHUB_REF_NAME\"}}" \
                      | gh api --method POST repos/zen-fs/docs/dispatches --input -
